# Commands to start on workspace startup
tasks:
  - init: docker-compose -f docker-compose.airbyte.yaml build
    command: docker-compose -f docker-compose.airbyte.yaml up
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-browser
  - port: 7233
    onOpen: ignore
