version: '3.1'

services:

  opendisco_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: opendisco
      POSTGRES_PASSWORD: opendisco
      POSTGRES_DB: opendisco
    ports:
      - 5432:5432