version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: opendisco
      POSTGRES_PASSWORD: opendisco
      POSTGRES_DB: opendisco
    ports:
      - 5432:5432

  web:
    user: "1000:1000"
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    command: python -m http.server --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
